### ISSUE TITLE
New blocks roadmap

### ISSUE THREAD

**Issue by KoshakMineDEV** [MemoriesOfTime/Nukkit-MOT#359]
# All this blocks are already added in [Lumi](https://github.com/KoshakMineDEV/Lumi) - MOT's fork aimed at more vanilla features, better API and performance

### 1.10
- [X] Stonecutter. #361 TODO: Functionality
### 1.18
- [X] Lighting Rod. #361 TODO: Functionality
### 1.17
- [X] Cut Copper Stairs
- [X] Cut Copper Slabs #494 
### 1.20
- [ ] Bamboo Door
- [ ] Bamboo Fence
- [ ] Cherry Door
- [ ] Cherry Fence
- [ ] Calibrated Sculk Sensor
- [ ] Chiseled Bookshelf
- [ ] Torchflower
- [ ] Pitched Plant
- [ ] Pitched Pod
- [ ] Bamboo Hanging Sign
- [ ] Oak Hanging Sign
- [ ] Spruce Hanging Sign
- [ ] Birch Hanging Sign
- [ ] Jungle Hanging Sign
- [ ] Acacia Hanging Sign
- [ ] Dark Oak Hanging Sign
- [ ] Mangrove Hanging Sign
- [ ] Cherry Hanging Sign
- [ ] Crimson Hanging Sign
- [ ] Warped Hanging Sign
- [X] Sniffer Egg #430 TODO: Functionality
### 1.21.0
- [ ] Chiseled Copper
- [ ] Copper Grate
- [ ] Copper Door
- [ ] Copper Trapdoor
- [ ] Tuff Stairs
- [ ] Tuff Slab
- [ ] Tuff Wall
- [ ] Chiseled Tuff
- [ ] Polished Tuff
- [ ] Polished Tuff Stairs
- [ ] Polished Tuff Slab
- [ ] Polished Tuff Wall
- [ ] Tuff Bricks
- [ ] Tuff Brick Stairs
- [ ] Tuff Brick Slab
- [ ] Tuff Brick Wall
- [ ] Chiseled Tuff Bricks
- [ ] Crafter
- [ ] Trial Spawner
- [ ] Ominous Trial Spawner
- [ ] Vault
- [ ] Heavy Core
### 1.21.50
- [ ] Pale Oak Log
- [ ] Pale Oak Wood
- [ ] Stripped Pale Oak Log
- [ ] Stripped Pale Oak Wood
- [ ] Pale Oak Leaves
- [ ] Pale Oak Sapling
- [ ] Pale Oak Planks
- [ ] Pale Oak Slab
- [ ] Pale Oak Stairs
- [ ] Pale Oak Door
- [ ] Pale Oak Trapdoor
- [ ] Pale Oak Button
- [ ] Pale Oak Pressure Plate
- [ ] Pale Oak Fence
- [ ] Pale Oak Fence Gate
- [ ] Pale Oak Sign
- [ ] Pale Oak Hanging Sign
- [ ] Pale Moss Block
- [ ] Pale Moss Carpet
- [ ] Pale Hanging Moss
- [ ] Eyeblossom
- [ ] Block of Resin
- [ ] Resin Bricks
- [ ] Resin Brick Stairs
- [ ] Resin Brick Slab
- [ ] Resin Brick Wall
- [ ] Chiseled Resin Bricks
- [ ] Creaking Heart

**Comment by KoshakMineDEV** [comment]
Not all blocks are done now so reopening
